@echo off
echo Initializing Git...
git init
echo Checking status...
git status
echo Adding files...
git add .
echo Committing...
git commit -m "ALL"
echo Adding remote...
git remote add origin https://github.com/n0ngXarm/Checkclass.git
echo Branching...
git branch -M main
echo Pushing...
git push -u origin main